
const o = document.querySelector.bind(document);
const oo = document.querySelectorAll.bind(document);

const app = {
    products: [
        {
            id: '1',
            type: 'hoaquadalat',
            name: 'Nho Đà Lạt xuất khẩu',
            price: '200.000',
            image: './assests/img/products/pd1.webp',
            color: 'purple',
            brand: 'Đà Lạt',
        },
        {
            id: '2',
            type: 'traicaynhapkhau',
            name: 'Táo New ZeaLand',
            price: '150.000',
            image: './assests/img/products/pd2.webp',
            color: '',
            brand: 'New ZeaLand',
        },
        {
            id: '3',
            type: 'traicaynhapkhau',
            name: 'Kiwi xanh',
            price: '250.000',
            image: './assests/img/products/pd3.webp',
            color: 'green',
            brand: 'Mỹ',
        },
        {
            id: '4',
            type: 'traicaynhapkhau',
            name: 'Chanh dây đỏ Úc',
            price: '400.000',
            image: './assests/img/products/pd4.webp',
            color: '',
            brand: 'Úc',
        },
        {
            id: '5',
            type: 'hoaquadalat',
            name: 'Dưa leo Đà Lạt',
            price: '50.000',
            image: './assests/img/products/pd5.webp',
            color: 'green',
            brand: 'Đà Lạt',
        },
        {
            id: '6',
            type: 'traicaynhapkhau',
            name: 'Nho Pháp không hạt',
            price: '300.000',
            image: './assests/img/products/pd6.webp',
            color: 'purple',
            brand: 'Pháp',
        },
        {
            id: '7',
            type: 'hoaquadalat',
            name: 'Ớt ngọt Đà Lạt',
            price: '80.000',
            image: './assests/img/products/pd7.webp',
            color: '',
            brand: 'Đà Lạt',
        },
        {
            id: '8',
            type: 'traicaynhapkhau',
            name: 'Mận Đào Úc',
            price: '180.000',
            image: './assests/img/products/pd8.webp',
            color: 'purple',
            brand: 'Úc',
        },
        {
            id: '9',
            name: 'Ớt chuông đỏ',
            price: '130.000',
            image: './assests/img/products/pd9.jpg',
            color: 'red',
            brand: 'Việt Nam',
        },
        {
            id: '10',
            name: 'Ớt chuông ngọt',
            price: '160.000',
            image: './assests/img/products/pd10.webp',
            color: '',
            brand: 'Việt Nam',
        },
        {
            id: '11',
            type: 'hoaquatuoi',
            name: 'Dâu tây',
            price: '100.000',
            image: './assests/img/products/pd11.webp',
            color: 'red',
            brand: 'Việt Nam',
        },
        {
            id: '12',
            name: 'Ớt sừng',
            price: '20.000',
            image: './assests/img/products/pd12.webp',
            color: 'red',
            brand: 'Việt Nam',
        },
        {
            id: '13',
            name: 'Ớt chuông vàng',
            price: '50.000',
            image: './assests/img/products/pd13.webp',
            color: 'yellow',
            brand: 'Việt Nam',
        },
        {
            id: '14',
            type: 'cacloaicuqua',
            name: 'Su su non',
            price: '80.000',
            image: './assests/img/products/pd14.jpg',
            color: 'green',
            brand: 'Việt Nam',
        },
        {
            id: '15',
            type: 'hoaquatuoi',
            name: 'Phúc bồn tử',
            price: '120.000',
            image: './assests/img/products/pd15.webp',
            color: '',
            brand: 'Việt Nam',
        },
        {
            id: '16',
            type: 'cacloaicuqua',
            name: 'Tỏi',
            price: '30.000',
            image: './assests/img/products/pd16.webp',
            color: 'white',
            brand: 'Việt Nam',
        },
        {
            id: '17',
            type: 'traicaynhapkhau',
            name: 'Cranberry',
            price: '150.000',
            image: './assests/img/products/pd17.webp',
            color: '',
            brand: 'Mỹ',
        },
        {
            id: '18',
            type: 'traicaynhapkhau',
            name: 'Acaiberry grandy',
            price: '2.500.000',
            image: './assests/img/products/pd18.webp',
            color: '',
            brand: 'Mỹ',
        },
        {
            id: '19',
            type: 'namcacloai',
            name: 'Nấm hương',
            price: '70.000',
            image: './assests/img/products/pd19.webp',
            color: 'white',
            brand: 'Việt Nam',
        },
        {
            id: '20',
            type: 'cacloaicuqua',
            name: 'Khoai môn',
            price: '140.000',
            image: './assests/img/products/pd20.webp',
            color: '',
            brand: 'Việt Nam',
        },
        {
            id: '21',
            type: 'cacloaicuqua',
            name: 'Khoai lang tím',
            price: '145.000',
            image: './assests/img/products/pd21.webp',
            color: 'purple',
            brand: 'Việt Nam',
        },
        {
            id: '22',
            type: 'cacloaicuqua',
            name: 'Hành củ',
            price: '32.000',
            image: './assests/img/products/pd22.webp',
            color: '',
            brand: 'Việt Nam',
        },
        {
            id: '23',
            type: 'cacloaicuqua',
            name: 'Khoai tây',
            price: '75.000',
            image: './assests/img/products/pd23.webp',
            color: '',
            brand: 'Việt Nam',
        },
        {
            id: '24',
            type: 'hoaquatuoi',
            name: 'Chuối xanh',
            price: '45.000',
            image: './assests/img/products/pd24.webp',
            color: 'green',
            brand: 'Việt Nam',
        },
        {
            id: '25',
            type: 'raunhapkhau',
            name: 'Cải xoăn',
            price: '55.000',
            image: './assests/img/products/pd25.jpg',
            color: 'green',
            brand: 'Việt Nam',
        },
        {
            id: '26',
            type: 'hoaquatuoi',
            name: 'Xoài cát Hòa Lộc',
            price: '125.000',
            image: './assests/img/products/pd25.webp',
            color: 'yellow',
            brand: 'Việt Nam',
        },
        {
            id: '27',
            type: 'hoaquatuoi',
            name: 'Táo xanh',
            price: '60.000',
            image: './assests/img/products/pd26.webp',
            color: 'green',
            brand: 'Việt Nam',
        },
        {
            id: '28',
            type: 'cacloaicuqua',
            name: 'Cà chua Beef',
            price: '50.000',
            image: './assests/img/products/pd27.webp',
            color: 'red',
            brand: 'Việt Nam',
        },
        {
            id: '29',
            type: 'cacloaicuqua',
            name: 'Hành tây',
            price: '31.000',
            image: './assests/img/products/pd28.webp',
            color: '',
            brand: 'Việt Nam',
        },
        {
            id: '30',
            type: 'traicaynhapkhau',
            name: 'Kiwi vàng',
            price: '105.000',
            image: './assests/img/products/pd29.webp',
            color: 'yellow',
            brand: 'Mỹ',
        },
        {
            id: '31',
            type: 'hoaquatuoi',
            name: 'Đu đủ ruột đỏ',
            price: '35.000',
            image: './assests/img/products/pd30.webp',
            color: '',
            brand: 'Việt Nam',
        },
        {
            id: '32',
            type: 'hoaquatuoi',
            name: 'Quả mâm xôi đen',
            price: '95.000',
            image: './assests/img/products/pd31.webp',
            color: '',
            brand: 'Việt Nam',
        },
        {
            id: '33',
            type: 'hoaquatuoi',
            name: 'Quýt ngọt',
            price: '32.000',
            image: './assests/img/products/pd32.webp',
            color: 'green',
            brand: 'Việt Nam',
        },
        {
            id: '34',
            type: 'raunhapkhau',
            name: 'Xà lách ICEBERG',
            price: '28.000',
            image: './assests/img/products/pd33.webp',
            color: 'green',
            brand: 'Úc',
        },
        {
            id: '35',
            type: 'cacloaicuqua',
            name: 'Khoai mỡ tím',
            price: '34.000',
            image: './assests/img/products/pd34.webp',
            color: 'purple',
            brand: 'Việt Nam',
        },
        {
            id: '36',
            type: 'namcacloai',
            name: "Nấm đùi gà Rica",
            price: "45.000",
            image: "./assests/img/nam_cac_loai/npd1.webp",
            color: 'white',
            brand: 'Rica',
          },
          {
            id: '37',
            type: 'namcacloai',
            name: "Nấm mối đen Rica",
            price: "85.000",
            image: "./assests/img/nam_cac_loai/npd2.webp",
            color: 'white',
            brand: 'Rica',
          },
          {
            id: '38',
            type: 'namcacloai',
            name: "Nấm kim châm Rica",
            price: "19.000",
            image: "./assests/img/nam_cac_loai/npd3.webp",
            color: 'white',
            brand: 'Rica',
          },
          {
            id: '39',
            type: 'namcacloai',
            name: "Nấm hoàng kim Rica",
            price: "37.000",
            image: "./assests/img/nam_cac_loai/npd4.webp",
            color: 'yellow',
            brand: 'Rica',
          },
          {
            id: '40',
            type: 'namcacloai',
            name: "Nấm hương Phú Gia",
            price: "109.000",
            image: "./assests/img/nam_cac_loai/npd5.webp",
            color: '',
            brand: 'Việt Nam',
          },
          {
            id: '41',
            type: 'namcacloai',
            name: "Nấm bào ngư xám Rica",
            price: "26.000",
            image: "./assests/img/nam_cac_loai/npd6.webp",
            color: 'white',
            brand: 'Rica',
          },
          {
            id: '42',
            type: 'namcacloai',
            name: "Nấm Porcini",
            price: "250.000",
            image: "./assests/img/nam_cac_loai/npd7.webp",
            color: '',
            brand: 'Việt Nam',
          },
          {
            id: '43',
            type: 'namcacloai',
            name: "Nấm Ngọc châm nâu",
            price: "150.000",
            image: "./assests/img/nam_cac_loai/npd8.webp",
            color: 'white',
            brand: 'Việt Nam',
          },
          {
            id: '44',
            type: 'rautuoisach',
            name: "Cần tây",
            price: "38.000",
            image: "./assests/img/rau/pd1.webp",
            color: 'green',
            brand: 'Việt Nam',
          },
          {
            id: '45',
            type: 'rautuoisach',
            name: "Cải ngọt hữu cơ",
            price: "27.000",
            image: "./assests/img/rau/pd2.webp",
            color: 'green',
            brand: 'Việt Nam',
          },
          {
            id: '46',
            type: 'taocacloai',
            name: 'Táo Breeze',
            price: '89.000',
            image: './assests/img/products/pd35.webp',
            color: 'red',
            brand: 'Mỹ',
          },
          {
            id: '47',
            type: 'taocacloai',
            name: 'Táo Envy',
            price: '99.000',
            image: './assests/img/products/pd36.webp',
            color: 'red',
            brand: 'Mỹ',
          },
          {
            id: '48',
            type: 'hoaquasaykho',
            name: 'Việt quất sấy khô',
            price: '98.000',
            image: './assests/img/hoaquasaykho/pd1.webp',
            color: '',
            brand: 'Việt Nam',
          },
          {
            id: '49',
            type: 'hoaquasaykho',
            name: 'Xoài sấy khô',
            price: '65.000',
            image: './assests/img/hoaquasaykho/pd2.webp',
            color: 'yellow',
            brand: 'Việt Nam',
          },
          {
            id: '50',
            type: 'hoaquasaykho',
            name: 'Cherry sấy khô',
            price: '184.000',
            image: './assests/img/products/pd37.webp',
            color: 'red',
            brand: 'Mỹ',
          },
    ],


    // render product
    render: function () {
        const htmls = this.products.map((product, index) => {
            return `
                        <div class="col l-2-4 m-4 c-6">
                            <a href="./productInformation.html?${product.id}" class="home__product-item">
                                <img src="${product.image}" alt='' class="home__product-item-img">
                                <h3 class="home__product-item-tittle">${product.name}</h3>
                                <h4 class="home__product-item-price">${product.price} ₫</h4>
                                <div class="home__product-item-btn-wrap">
                                    <button class="home__product-item-btn btn btn--primary ">Xem chi tiết</button>
                                </div>
                            </a>
                        </div>
                    `
        })

        o('.home__product-item-wrap').innerHTML = htmls.join('');
    },

    start: function () {
        this.render();
    }
}

app.start();
